name: 🚀 Deploy (multi-env)

on:
  push:
    branches: [ main, homol, develop ]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - branch: main
            remote_env: prod
          - branch: homol
            remote_env: homol
          - branch: develop
            remote_env: dev

    concurrency:
      group: deploy-${{ matrix.remote_env }}
      cancel-in-progress: false

    env:
      # Repository Variables
      REMOTE_CHEMIN: ${{ secrets.REMOTE_CHEMIN }}
      ADRESSE_GLOBAL: ${{ vars.ADRESSE_GLOBAL }}
      ADRESSE_LOCAL: ${{ vars.ADRESSE_LOCAL }}
      # Env cible depuis la matrice
      REMOTE_ENV: ${{ matrix.remote_env }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Contexte (echo)
        if: ${{ github.ref_name == matrix.branch }}
        run: |
          echo "Branch        : $GITHUB_REF_NAME"
          echo "REMOTE_ENV    : $REMOTE_ENV"
          echo "REMOTE_CHEMIN : $REMOTE_CHEMIN"
          echo "ADRESSE_GLOBAL: $ADRESSE_GLOBAL"
          echo "ADRESSE_LOCAL : $ADRESSE_LOCAL"

      - name: Build remote path (normalized)
        id: path
        if: ${{ github.ref_name == matrix.branch }}
        run: |
          # Normalisation des / pour éviter doubles/manquants
          RC="${REMOTE_CHEMIN%/}"
          AG="${ADRESSE_GLOBAL%/}"
          AL="${ADRESSE_LOCAL#/}"
          DEST="$RC/$AG/$REMOTE_ENV/$AL/"
          echo "DEST=$DEST" >> "$GITHUB_OUTPUT"
          echo "Chemin distant : $DEST"

      - name: Deploy via rsync
        if: ${{ github.ref_name == matrix.branch }}
        run: |
          # Utilise .rsync-ignore si présent, sinon sans exclude
          EXCLUDE=""
          [[ -f .rsync-ignore ]] && EXCLUDE="--exclude-from=.rsync-ignore"

          rsync -avz --delete $EXCLUDE \
            ./ \
            "${{ steps.path.outputs.DEST }}"