name: 🔗 Link issues to PR (dynamic)

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review, reopened]

permissions:
  contents: read
  pull-requests: write

env:
  # One-line regex, antislashs échappés.
  TICKET_REGEX: '(?:\\B#(?<num>\\d+)\\b|[A-Z][A-Z0-9_]+-(?<num>\\d+)\\b|(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\\s+#(?<num>\\d+)|ticket[-_ ]?(?<num>\\d+)\\b)'

jobs:
  link:
    runs-on: ubuntu-latest
    steps:
      - name: Detect & link issues in PR body
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const ticketRe = new RegExp(process.env.TICKET_REGEX, 'ig');
            const strongVerbRe = /\b(fix(?:es|ed)?|close(?:s|d)?|resolve(?:s|d)?)\b/i;

            const branch = pr.head.ref || '';
            const title  = pr.title || '';
            let body     = pr.body || '';

            const commits = await github.paginate(
              github.rest.pulls.listCommits,
              { owner, repo, pull_number: pr.number, per_page: 100 }
            );
            const commitMessages = commits.map(c => c.commit.message).join('\n');

            const haystack = [branch, title, body, commitMessages].join('\n');

            const found = new Set();
            for (const m of haystack.matchAll(ticketRe)) {
              const n = (m.groups && m.groups.num) ? m.groups.num : (m[1] || (m[0].match(/\d+/) || [])[0]);
              if (n && /^\d+$/.test(n)) found.add(Number(n));
            }

            if (found.size === 0) {
              core.setFailed(
                'Cette PR n’est liée à aucun ticket/issue détecté.\n' +
                'Accepte l’un des critères : Closes #123 | titre PROJ-123 | branche ticket-123.'
              );
              return;
            }

            const useFixes = strongVerbRe.test(haystack);

            const already = new Set();
            const bodyLower = body.toLowerCase();
            for (const n of found) {
              if (bodyLower.includes(`#${n}`)) already.add(n);
            }

            const toAdd = [...found].filter(n => !already.has(n));
            if (toAdd.length === 0) {
              console.log('Tous les tickets détectés sont déjà référencés dans la PR.');
              return;
            }

            const prefix = useFixes ? 'Fixes' : 'Related to';
            const lines = toAdd.map(n => `${prefix} #${n}`).join('\n');
            const separator = body.trim().length ? '\n\n' : '';
            const newBody = `${body}${separator}<!-- auto-linked by workflow -->\n${lines}\n`;

            await github.rest.pulls.update({
              owner, repo,
              pull_number: pr.number,
              body: newBody
            });

            console.log(`Ajouté dans la PR: ${lines}`);
