name: PR requires linked issue

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


permissions:
  contents: read
  pull-requests: read
  issues: read

jobs:
  check-linked-issue:
    runs-on: ubuntu-latest
    env:
  # Exemples 2 pris en charge :
  #  - #123
  #  - PROJ-1234
  #  - close/fix/resolve #123
  #  - ticket-123  | ticket 123 | ticket_123   ← (NOUVEAU)
      TICKET_REGEX: '(?:\\B#(?<num>\\d+)\\b|[A-Z][A-Z0-9_]+-(?<num>\\d+)\\b|(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\\s+#(?<num>\\d+)|ticket[-_ ]?(?<num>\\d+)\\b)'
    steps:
      - name: Vérifier les liaisons via GraphQL + regex
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pr = context.payload.pull_request;
            const prNumber = pr.number;

            // 1) Cherche issues liées via closing keywords dans le body (fallback texte brut)
            const body = (pr.body || "").toLowerCase();
            const closingKeywordRegex = /\b(close[sd]?|fix(e[sd])?|resolve[sd]?)\s+#\d+\b/gi;
            const hasClosingKeyword = closingKeywordRegex.test(body);

            // 2) Interroge l’API GraphQL pour closingIssuesReferences (les issues que GitHub fermera à la merge)
            const query = `
              query($owner:String!, $repo:String!, $number:Int!) {
                repository(owner:$owner, name:$repo) {
                  pullRequest(number:$number) {
                    closingIssuesReferences(first: 20) {
                      nodes { number url title }
                    }
                  }
                }
              }
            `;
            const data = await github.graphql(query, { owner, repo, number: prNumber });
            const closing = data?.repository?.pullRequest?.closingIssuesReferences?.nodes ?? [];
            const hasClosingIssuesRefs = closing.length > 0;

            // 3) Vérifie titre et branche contre un regex de ticket configurable
            const ticketPattern = new RegExp(process.env.TICKET_REGEX, 'i');
            const title = pr.title || "";
            const headRef = pr.head?.ref || "";
            const hasTicketInTitle = ticketPattern.test(title);
            const hasTicketInBranch = ticketPattern.test(headRef);

            // Résumé pour logs
            core.info(`PR #${prNumber} — title="${title}" branch="${headRef}"`);
            core.info(`closingIssuesReferences: ${closing.length}`);
            closing.forEach(i => core.info(`- closes #${i.number} ${i.url}`));
            core.info(`hasClosingKeyword=${hasClosingKeyword}, hasTicketInTitle=${hasTicketInTitle}, hasTicketInBranch=${hasTicketInBranch}`);

            const ok = hasClosingIssuesRefs || hasClosingKeyword || hasTicketInTitle || hasTicketInBranch;

            if (!ok) {
              const tips = [
                "🧩 Lier une issue avec un mot-clé dans la description, p.ex. `Closes #123`",
                "🏷️ Inclure l’identifiant du ticket dans le *titre* de la PR, p.ex. `PROJ-1234: Corrige le bug X`",
                "🌿 Inclure l’identifiant du ticket dans le *nom de branche*, p.ex. `feature/PROJ-1234/…`",
              ].join("\\n");

              core.setFailed(
                "Cette PR n’est liée à aucun ticket/issue détecté.\n\n" +
                "Accepte l’un des critères suivants :\n" + tips + "\n\n" +
                `Regex utilisé: ${process.env.TICKET_REGEX}`
              );
            } else {
              core.info("✅ PR liée à un ticket/issue : contrôle validé.");
            }
